export const mockPod = {
  _id: 'pod123',
  title: 'DesignCraft Studio',
  subtitle: 'Building the next generation of UI/UX tools',
  banner: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800',
  owner: {
    _id: 'user1',
    name: 'Ravindra',
    avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=ravindra',
  },
  tags: ['Design', 'Development', 'Startup'],
  visibility: 'public',
  moderators: ['user3', 'user5'],
  roles: [
    {
      _id: 'role1',
      name: 'UI Designer',
      description: 'Create beautiful interfaces',
      capacity: 6,
      filled: 4,
    },
    {
      _id: 'role2',
      name: 'Frontend Developer',
      description: 'Build responsive web apps',
      capacity: 4,
      filled: 2,
    },
    {
      _id: 'role3',
      name: 'Backend Developer',
      description: 'Develop scalable APIs',
      capacity: 3,
      filled: 2,
    },
    {
      _id: 'role4',
      name: 'Product Manager',
      description: 'Define product strategy',
      capacity: 2,
      filled: 2,
    },
  ],
  members: [
    {
      userId: 'user1',
      name: 'Ravindra (You)',
      avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=ravindra',
      role: 'Product Manager',
      joinedAt: '2025-11-01T10:00:00Z',
      isModerator: false,
    },
    {
      userId: 'user3',
      name: 'Priya Singh',
      avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=priya',
      role: 'UI Designer',
      joinedAt: '2025-11-05T14:30:00Z',
      isModerator: true,
    },
    {
      userId: 'user5',
      name: 'Arjun Verma',
      avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=arjun',
      role: 'Frontend Developer',
      joinedAt: '2025-11-08T09:15:00Z',
      isModerator: true,
    },
    {
      userId: 'user2',
      name: 'Rohit Sharma',
      avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=rohit',
      role: 'UI Designer',
      joinedAt: '2025-11-10T11:20:00Z',
      isModerator: false,
    },
    {
      userId: 'user4',
      name: 'Sneha Reddy',
      avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=sneha',
      role: 'Backend Developer',
      joinedAt: '2025-11-12T16:45:00Z',
      isModerator: false,
    },
    {
      userId: 'user6',
      name: 'Karan Mehta',
      avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=karan',
      role: 'Frontend Developer',
      joinedAt: '2025-11-14T08:30:00Z',
      isModerator: false,
    },
    {
      userId: 'user7',
      name: 'Ananya Gupta',
      avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=ananya',
      role: 'UI Designer',
      joinedAt: '2025-11-15T13:15:00Z',
      isModerator: false,
    },
    {
      userId: 'user8',
      name: 'Vikram Patel',
      avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=vikram',
      role: 'Backend Developer',
      joinedAt: '2025-11-16T10:00:00Z',
      isModerator: false,
    },
    {
      userId: 'user9',
      name: 'Meera Desai',
      avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=meera',
      role: 'Product Manager',
      joinedAt: '2025-11-17T14:20:00Z',
      isModerator: false,
    },
    {
      userId: 'user10',
      name: 'Aditya Kumar',
      avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=aditya',
      role: 'UI Designer',
      joinedAt: '2025-11-18T09:45:00Z',
      isModerator: false,
    },
  ],
  applicants: [
    {
      _id: 'app1',
      userId: 'user11',
      name: 'Aarya Patel',
      avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=aarya',
      role: 'UI Designer',
      message:
        'I have 3 years of experience in Figma and love creating clean interfaces',
      appliedAt: '2025-11-18T10:30:00Z',
    },
    {
      _id: 'app2',
      userId: 'user12',
      name: 'Karan Malhotra',
      avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=karanm',
      role: 'Frontend Developer',
      message: 'React expert, built 10+ production apps',
      appliedAt: '2025-11-17T14:20:00Z',
    },
  ],
  invites: [
    {
      _id: 'inv1',
      userId: 'user15',
      name: 'Neha Gupta',
      avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=neha',
      role: 'UI Designer',
      invitedAt: '2025-11-16T09:00:00Z',
      status: 'pending',
    },
  ],
  activities: [
    {
      _id: 'act1',
      type: 'member_joined',
      user: 'Aditya Kumar',
      role: 'UI Designer',
      timestamp: '2025-11-18T09:45:00Z',
    },
    {
      _id: 'act2',
      type: 'application_received',
      user: 'Aarya Patel',
      role: 'UI Designer',
      timestamp: '2025-11-18T10:30:00Z',
    },
    {
      _id: 'act3',
      type: 'member_joined',
      user: 'Meera Desai',
      role: 'Product Manager',
      timestamp: '2025-11-17T14:20:00Z',
    },
    {
      _id: 'act4',
      type: 'invite_sent',
      user: 'Neha Gupta',
      role: 'UI Designer',
      timestamp: '2025-11-16T09:00:00Z',
    },
    {
      _id: 'act5',
      type: 'member_joined',
      user: 'Vikram Patel',
      role: 'Backend Developer',
      timestamp: '2025-11-16T10:00:00Z',
    },
  ],
};
