export interface SearchableUser {
  id: string;
  name: string;
  avatar: string;
  bio?: string;
}

export const mockUsers: SearchableUser[] = [
  // High-quality Indian names with dicebear avatars
  { id: 'user11', name: 'Neha Gupta', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=neha', bio: 'Product Designer at Figma' },
  { id: 'user12', name: 'Sanjay Kumar', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=sanjay', bio: 'Full-stack Developer' },
  { id: 'user13', name: 'Riya Shah', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=riya', bio: 'UI/UX Designer' },
  { id: 'user14', name: 'Amit Patel', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=amit', bio: 'Frontend Engineer' },
  { id: 'user15', name: 'Kavya Reddy', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=kavya', bio: 'Backend Developer' },
  { id: 'user16', name: 'Rajesh Iyer', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=rajesh', bio: 'DevOps Engineer' },
  { id: 'user17', name: 'Pooja Nair', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=pooja', bio: 'Product Manager' },
  { id: 'user18', name: 'Varun Sharma', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=varun', bio: 'Mobile Developer' },
  { id: 'user19', name: 'Simran Kaur', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=simran', bio: 'Data Scientist' },
  { id: 'user20', name: 'Arun Menon', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=arun', bio: 'Machine Learning Engineer' },
  { id: 'user21', name: 'Divya Pillai', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=divya', bio: 'UX Researcher' },
  { id: 'user22', name: 'Karthik Rao', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=karthik', bio: 'Software Architect' },
  { id: 'user23', name: 'Anjali Desai', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=anjali', bio: 'Growth Marketer' },
  { id: 'user24', name: 'Vishal Joshi', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=vishal', bio: 'iOS Developer' },
  { id: 'user25', name: 'Shreya Agarwal', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=shreya', bio: 'Content Designer' },
  { id: 'user26', name: 'Nikhil Bhat', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=nikhil', bio: 'Security Engineer' },
  { id: 'user27', name: 'Tanvi Malhotra', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=tanvi', bio: 'Design Lead' },
  { id: 'user28', name: 'Rahul Kapoor', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=rahul', bio: 'Engineering Manager' },
  { id: 'user29', name: 'Megha Srinivasan', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=megha', bio: 'Brand Designer' },
  { id: 'user30', name: 'Aditya Varma', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=adityav', bio: 'Cloud Architect' },
  { id: 'user31', name: 'Ishita Chopra', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=ishita', bio: 'Technical Writer' },
  { id: 'user32', name: 'Rohan Mishra', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=rohan', bio: 'Android Developer' },
  { id: 'user33', name: 'Nidhi Saxena', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=nidhi', bio: 'Marketing Manager' },
  { id: 'user34', name: 'Akash Pandey', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=akash', bio: 'Solutions Architect' },
  { id: 'user35', name: 'Prachi Jain', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=prachi', bio: 'Sales Engineer' },
  { id: 'user36', name: 'Sidharth Kulkarni', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=sidharth', bio: 'QA Lead' },
  { id: 'user37', name: 'Ritu Bansal', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=ritu', bio: 'HR Manager' },
  { id: 'user38', name: 'Gaurav Sinha', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=gaurav', bio: 'Business Analyst' },
  { id: 'user39', name: 'Swati Yadav', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=swati', bio: 'Operations Lead' },
  { id: 'user40', name: 'Manish Bhardwaj', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=manish', bio: 'Customer Success' },
  { id: 'user41', name: 'Deepika Chatterjee', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=deepika', bio: 'Finance Manager' },
  { id: 'user42', name: 'Arjit Singh', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=arjit', bio: 'Legal Counsel' },
  { id: 'user43', name: 'Sonam Khanna', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=sonam', bio: 'Recruiter' },
  { id: 'user44', name: 'Yash Mehta', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=yash', bio: 'Community Manager' },
  { id: 'user45', name: 'Aarti Vyas', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=aarti', bio: 'Project Coordinator' },
  { id: 'user46', name: 'Sahil Garg', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=sahil', bio: 'DevRel Engineer' },
  { id: 'user47', name: 'Kritika Tiwari', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=kritika', bio: 'Compliance Officer' },
  { id: 'user48', name: 'Harsh Aggarwal', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=harsh', bio: 'Partnership Lead' },
  { id: 'user49', name: 'Pallavi Rao', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=pallavi', bio: 'Event Manager' },
  { id: 'user50', name: 'Kunal Dixit', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=kunal', bio: 'Support Engineer' },
  // Add 50 more for comprehensive search testing
  { id: 'user51', name: 'Anushka Patil', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=anushka' },
  { id: 'user52', name: 'Tushar Gupta', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=tushar' },
  { id: 'user53', name: 'Kriti Sharma', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=kriti' },
  { id: 'user54', name: 'Dhruv Malhotra', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=dhruv' },
  { id: 'user55', name: 'Ritika Verma', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=ritika' },
  { id: 'user56', name: 'Ayush Pandey', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=ayush' },
  { id: 'user57', name: 'Shivani Reddy', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=shivani' },
  { id: 'user58', name: 'Aryan Joshi', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=aryan' },
  { id: 'user59', name: 'Tanya Kapoor', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=tanya' },
  { id: 'user60', name: 'Vihaan Nair', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=vihaan' },
  { id: 'user61', name: 'Sanya Iyer', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=sanya' },
  { id: 'user62', name: 'Kabir Mehta', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=kabir' },
  { id: 'user63', name: 'Diya Agarwal', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=diya' },
  { id: 'user64', name: 'Reyansh Kulkarni', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=reyansh' },
  { id: 'user65', name: 'Aarohi Sinha', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=aarohi' },
  { id: 'user66', name: 'Shivansh Rao', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=shivansh' },
  { id: 'user67', name: 'Myra Desai', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=myra' },
  { id: 'user68', name: 'Advait Bansal', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=advait' },
  { id: 'user69', name: 'Saanvi Chopra', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=saanvi' },
  { id: 'user70', name: 'Aarav Kumar', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=aarav' },
  { id: 'user71', name: 'Pari Saxena', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=pari' },
  { id: 'user72', name: 'Vivaan Shah', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=vivaan' },
  { id: 'user73', name: 'Kiara Pillai', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=kiara' },
  { id: 'user74', name: 'Atharv Jain', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=atharv' },
  { id: 'user75', name: 'Navya Mishra', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=navya' },
  { id: 'user76', name: 'Rudra Varma', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=rudra' },
  { id: 'user77', name: 'Aanya Bhatt', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=aanya' },
  { id: 'user78', name: 'Shaurya Garg', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=shaurya' },
  { id: 'user79', name: 'Ira Tiwari', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=ira' },
  { id: 'user80', name: 'Aditya Bhardwaj', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=adityab' },
  { id: 'user81', name: 'Shanaya Yadav', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=shanaya' },
  { id: 'user82', name: 'Ishaan Khanna', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=ishaan' },
  { id: 'user83', name: 'Anaya Vyas', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=anaya' },
  { id: 'user84', name: 'Arnav Chatterjee', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=arnav' },
  { id: 'user85', name: 'Anika Dixit', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=anika' },
  { id: 'user86', name: 'Sai Aggarwal', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=sai' },
  { id: 'user87', name: 'Riya Srinivasan', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=riyasr' },
  { id: 'user88', name: 'Ved Patil', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=ved' },
  { id: 'user89', name: 'Sara Menon', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=sara' },
  { id: 'user90', name: 'Pranav Kulkarni', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=pranav' },
  { id: 'user91', name: 'Avni Pandey', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=avni' },
  { id: 'user92', name: 'Arjun Malhotra', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=arjunm' },
  { id: 'user93', name: 'Maira Gupta', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=maira' },
  { id: 'user94', name: 'Naman Shah', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=naman' },
  { id: 'user95', name: 'Zara Reddy', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=zara' },
  { id: 'user96', name: 'Ayaan Kapoor', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=ayaan' },
  { id: 'user97', name: 'Aadhya Sharma', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=aadhya' },
  { id: 'user98', name: 'Ranveer Nair', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=ranveer' },
  { id: 'user99', name: 'Aditi Iyer', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=aditi' },
  { id: 'user100', name: 'Lakshya Desai', avatar: 'https://api.dicebear.com/7.x/avataaars/png?seed=lakshya' },
];
